# For 64-bit Raspberry Pi device types (Pi3-64/4-64)
# we can use the 32-bit ARM version to take advantage
# of Rapsbian packages (which are 32-bit only at the moment)
FROM balenalib/raspberrypi3-debian:buster

WORKDIR /usr/src/app

RUN install_packages \
      sense-hat \
      raspberrypi-bootloader \
      python-numpy

COPY * ./

CMD ["bash", "start.sh"]
