FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:buster

WORKDIR /usr/src/app

RUN install_packages \
      sense-hat \
      raspberrypi-bootloader \
      python-numpy

COPY * ./

CMD ["bash", "start.sh"]
