FROM resin/%%RESIN_MACHINE_NAME%%-debian:jessie-20170201

WORKDIR /usr/src/app
ENV INITSYSTEM on

RUN apt-get update && \
    apt-get install -yq --no-install-recommends \
      sense-hat \
      raspberrypi-bootloader \
      python-numpy \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY * ./

CMD ["bash", "start.sh"]
